version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:23.1.0  # Change to the appropriate image for your project
    steps:
      - browser-tools/install-browser-tools
      - checkout  # Check out the source code

      - run:
          name: Install dependencies
          command: |
            # For example, installing dependencies for a Python project
            npm install

      - run:
          name: Run SonarQube Scanner
          command: |
            # Install SonarQube scanner (use the appropriate version)
            curl -sSLo sonarqube-scanner.zip https://github.com/SonarSource/sonar-scanner-cli/releases/download/4.6.2.2472/sonar-scanner-cli-4.6.2.2472-linux.zip
            unzip sonarqube-scanner.zip
            export SONARQUBE_SCANNER_HOME=$(pwd)/sonar-scanner-4.6.2.2472-linux
            export PATH=$SONARQUBE_SCANNER_HOME/bin:$PATH

            # Run the SonarQube scanner
            sonar-scanner \
              -Dsonar.projectKey=vcstdn2024 \
              -Dsonar.sources=. \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN  # This will use the secret stored in GitHub

workflows:
  version: 2
  build_and_scan:
    jobs:
      - build
